- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Permitir SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Permitir HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Permitir HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Activar UFW
  ufw:
    state: enabled
    policy: deny
