- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create directory
  file:
    path: /var/www/html/basic-index
    state: directory
    mode: '0755'

- name: Copy "index.html" to default Nginx location
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: 0644

- name: Enable default Nginx website
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

