Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"    # base image
  config.vm.hostname = "ansible-vm"   # VM hostname
  config.vm.network "private_network", ip: "192.168.56.10"
  # Vagrant uses Ansible to configure the VM
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventories/vagrant/hosts.ini"
  end
end
