Vagrant.configure("2") do |config|                         #
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "nginx-basic"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory.ini"
    ansible.limit = "all"
    ansible.verbose = "v"
  end

  # La siguiente configuración instala Ansible en la VM de VB
  #config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "/vagrant/playbook.yml"
  #end
end
